import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
normal = { family = "MesloLGS Nerd Font Mono", style = "Regular" }
size = 20

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.93

[window.padding]
x = 5
y = 5

[keyboard]
bindings = [
  { key = "R", mods = "Control|Shift", action = "ResetFontSize" },
  { key = "_", mods = "Control|Shift", action = "DecreaseFontSize" },
  { key = "_", mods = "Control|Shift", action = "DecreaseFontSize" },
  { key = "_", mods = "Control|Shift", action = "DecreaseFontSize" },
  { key = "_", mods = "Control|Shift", action = "DecreaseFontSize" },
  { key = "_", mods = "Control|Shift", action = "DecreaseFontSize" },
  { key = "_", mods = "Control|Shift", action = "DecreaseFontSize" },
  { key = "_", mods = "Control|Shift", action = "DecreaseFontSize" },
  { key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
]
